# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DMVDriverTestUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# imports

from PyQt5 import QtCore, QtGui, QtWidgets
from quiz_list import Quiz_list
from choiceimq import ChoiceImageQuestion


class DMVTestUI(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow, ql):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 900)
        self.setFixedHeight(900)
        self.setFixedWidth(1000)
        self._central_widget = QtWidgets.QWidget(MainWindow)
        self._central_widget.setObjectName("_central_widget")
        self.gridLayout = QtWidgets.QGridLayout(self._central_widget)
        self.gridLayout.setObjectName("gridLayout")
        self._quit = QtWidgets.QPushButton(self._central_widget)
        self._quit.setObjectName("_quit")
        self.gridLayout.addWidget(self._quit, 4, 2, 1, 1)
        self._photo = QtWidgets.QLabel(self._central_widget)
        self._photo.setObjectName("_photo")
        self.gridLayout.addWidget(self._photo, 0, 0, 1, 3)
        self._question = QtWidgets.QLabel(self._central_widget)
        self._question.setObjectName("_question")
        self.gridLayout.addWidget(self._question, 1, 0, 1, 3)

        self._comments = QtWidgets.QLabel(self._central_widget)
        self._comments.setObjectName("_comments")
        self.gridLayout.addWidget(self._comments, 3, 0, 1, 3)

        self._num_correct = QtWidgets.QLabel(self._central_widget)
        self._num_correct.setObjectName("_num_correct")
        self.gridLayout.addWidget(self._num_correct, 4, 0, 1, 1)
        self._next = QtWidgets.QPushButton(self._central_widget)
        self._next.setObjectName("_next")
        self.gridLayout.addWidget(self._next, 4, 1, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapAllRows)
        self.formLayout.setObjectName("formLayout")
        self._answer1 = QtWidgets.QRadioButton(self._central_widget)
        self._answer1.setObjectName("_answer1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self._answer1)
        self._answer2 = QtWidgets.QRadioButton(self._central_widget)
        self._answer2.setObjectName("_answer2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self._answer2)
        self._answer3 = QtWidgets.QRadioButton(self._central_widget)
        self._answer3.setObjectName("_answer3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self._answer3)
        self._answer4 = QtWidgets.QRadioButton(self._central_widget)
        self._answer4.setObjectName("_answer4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self._answer4)
        self.gridLayout.addLayout(self.formLayout, 2, 0, 1, 3)
        MainWindow.setCentralWidget(self._central_widget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 460, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Creates a Quiz_list of the questions, grabs the next question,
        # creates a variable for num correct and sets buttons ready
        self._quiz_list = Quiz_list(ql)
        self._cur_question = next(self._quiz_list)
        self._correct = 0
        self._enabled = False

        self._num_correct.setText(f"{'Question'} {self._quiz_list.index() + 1} {'of'} {self._quiz_list.size()}{'   | Correct: '}{self._correct}{' / '}{self._quiz_list.size()}")
        self.set_ui()

        self._answer1.clicked.connect(self.checking_1)
        self._answer2.clicked.connect(self.checking_2)
        self._answer3.clicked.connect(self.checking_3)
        self._answer4.clicked.connect(self.checking_4)

        self._next.clicked.connect(self.go_next)
        self._quit.clicked.connect(self.close)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DMV Driver Test"))
        self._quit.setText(_translate("MainWindow", "Quit Quiz"))
        self._next.setText(_translate("MainWindow", "Next Question"))
        self._question.setStyleSheet("font-size:20px;font-weight:600")
        self._answer1.setStyleSheet("font-size:18px;font-weight:400")
        self._answer2.setStyleSheet("font-size:18px;font-weight:400")
        self._answer3.setStyleSheet("font-size:18px;font-weight:400")
        self._answer4.setStyleSheet("font-size:18px;font-weight:400")
        self._comments.setStyleSheet("font-size:16px;font-weight:400")
        self._num_correct.setStyleSheet("font-size:16px;font-weight:400")
        self._comments.setWordWrap(True)
        self._question.setWordWrap(True)

    # Sets up UI for next question
    def set_ui(self):
        self._comments.setVisible(False)

        self._answer1.setText(self._cur_question._choices[0].strip())
        self._answer2.setText(self._cur_question._choices[1].strip())
        self._answer3.setText(self._cur_question._choices[2].strip())
        self._answer4.setText(self._cur_question._choices[3].strip())
        self._question.setText(self._cur_question._question_text.strip())

        # Determintes if the next question has a picture and shows/hides picture label 
        if isinstance(self._cur_question, ChoiceImageQuestion):
            self.load_image()
            self._pic_label.setVisible(True)
            self._photo.setVisible(True)

        else:
            self._pic_label.setVisible(False)
            self._photo.setVisible(False)
            

    def load_image(self):
        my_image = QtGui.QImage()
        my_image.loadFromData(self._cur_question._img_bytes) 
        self._pic_label = QtWidgets.QLabel(self._photo) 
        w = 1000
        h = 200
        pixmap = QtGui.QPixmap.fromImage(my_image)
        scaled_img = pixmap.scaled(w, h, QtCore.Qt.KeepAspectRatio)
        self._pic_label.setPixmap(pixmap)

    # Function called by next button to set up the next question of the test
    def go_next(self):
        # Cannot be clicked if question has not been answered
        if not self._enabled:
            pass
        else:
            # Use next function from Quiz_List to get next question
            self._cur_question = next(self._quiz_list)
            # if the last question go to end screen
            if self._cur_question is None:
                self.end_screen()
            # If not then update score, show next question, and unlock buttons
            else:
                self._num_correct.setText(f"{'Question'} {self._quiz_list.index() + 1} {'of'} {self._quiz_list.size()}{'   | Correct: '}{self._correct}{' / '}{self._quiz_list.size()}")
                self.set_ui()
                self.reset_buttons()
                self.button_enabler()

    # All checking functions call button_enabler and add one to score if correct
    def checking_1(self):
        self.button_enabler()
        if self._cur_question.check_answer(self._answer1.text()):
            self._correct += 1


    def checking_2(self):
        self.button_enabler()
        if self._cur_question.check_answer(self._answer2.text()):
            self._correct += 1

    def checking_3(self):
        self.button_enabler()
        if self._cur_question.check_answer(self._answer3.text()):
            self._correct += 1

    def checking_4(self):
        self.button_enabler()
        if self._cur_question.check_answer(self._answer4.text()):
            self._correct += 1

    # Locks/Unlocks all buttons based on if a button has been click or
    # the next button has been clicked 
    def button_enabler(self):
        self._enabled = not self._enabled
        self._answer1.setDisabled(self._enabled)
        self._answer2.setDisabled(self._enabled)
        self._answer3.setDisabled(self._enabled)
        self._answer4.setDisabled(self._enabled)
        self._comments.setVisible(self._enabled)
        self._comments.setText(self._cur_question._answer_comments.strip())

    # Resets buttons from being clicked on last question
    def reset_buttons(self):
        self._answer1.setCheckable(False)
        self._answer2.setCheckable(False)
        self._answer3.setCheckable(False)
        self._answer4.setCheckable(False)
        self._answer1.setCheckable(True)
        self._answer2.setCheckable(True)
        self._answer3.setCheckable(True)
        self._answer4.setCheckable(True)

    def end_screen(self):
        # Hide existing elements
        self._answer1.setVisible(False)
        self._answer2.setVisible(False)
        self._answer3.setVisible(False)
        self._answer4.setVisible(False)
        self._next.setVisible(False)
        self._photo.setVisible(False)
        self._pic_label.setVisible(False)
        self._comments.setVisible(False)
        self._num_correct.setVisible(False)

        # Update and display the score in the center
        self._question.setAlignment(QtCore.Qt.AlignCenter)
        self._question.setText(f"Your Score is {self._correct} out of {self._quiz_list.size()}")
        self._question.setStyleSheet("font-size: 20px; font-weight: bold;")
        self._question.setVisible(True)

        # Display a congratulatory message
        self._comments.setText("Congratulations on completing the test!")
        self._comments.setAlignment(QtCore.Qt.AlignCenter)
        self._comments.setStyleSheet("font-size: 18px; color: green; margin-top: 20px;")
        self._comments.setVisible(True)
