# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'doctor_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from doctor import Doctor


class Doc_pop(QtWidgets.QDialog):
    def setupUi(self, popup):
        popup.setObjectName("popup")
        popup.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(popup)
        self.gridLayout.setObjectName("gridLayout")
        self.popup_buttons = QtWidgets.QDialogButtonBox(popup)
        self.popup_buttons.setOrientation(QtCore.Qt.Horizontal)
        self.popup_buttons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.popup_buttons.setObjectName("popup_buttons")
        self.gridLayout.addWidget(self.popup_buttons, 6, 0, 1, 1)
        self.popup_label = QtWidgets.QLabel(popup)
        self.popup_label.setObjectName("popup_label")
        self.gridLayout.addWidget(self.popup_label, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(popup)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 1)

        self.retranslateUi(popup)
        self.popup_buttons.accepted.connect(self.submit) # type: ignore
        self.popup_buttons.rejected.connect(popup.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(popup)
        self._selected_doctor = ""

    def retranslateUi(self, popup):
        _translate = QtCore.QCoreApplication.translate
        popup.setWindowTitle(_translate("popup", "Dialog"))

    def display_docs(self, doctors):
        for doc in doctors:
            self.comboBox.addItem(doc.get_full_name())

    def submit(self):
        self._selected_doctor = self.comboBox.currentText()
        self.accept()