# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_doctor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from db_search import find_doctors, get_all_doctors
from doctor_popup import Doc_pop
import sys
from doctor import Doctor
from doctor_list import Doc_list


class Main_ui(QtWidgets.QMainWindow):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(700, 700)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.grid_layout = QtWidgets.QGridLayout()
        self.grid_layout.setObjectName("grid_layout")
        self.input_line = QtWidgets.QLineEdit(self.centralwidget)
        self.input_line.setText("")
        self.input_line.setObjectName("input_line")

        self.grid_layout.addWidget(self.input_line, 0, 0, 1, 1)
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setObjectName("search_button")
        self.grid_layout.addWidget(self.search_button, 0, 1, 1, 1)
        self.search_button.clicked.connect(self.searched)

        self.gridLayout_2.addLayout(self.grid_layout, 0, 0, 1, 4)
        self.photo_frame = QtWidgets.QFrame(self.centralwidget)
        self.photo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.photo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.photo_frame.setObjectName("photo_frame")

        self.gridLayout_2.addWidget(self.photo_frame, 1, 0, 1, 2)
        self.form_layout = QtWidgets.QFormLayout()
        self.form_layout.setObjectName("form_layout")
        self.first_n_label = QtWidgets.QLabel(self.centralwidget)
        self.first_n_label.setObjectName("first_n_label")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.first_n_label)
        self.first_n_out = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.first_n_out.sizePolicy().hasHeightForWidth())
        self.first_n_out.setSizePolicy(sizePolicy)
        self.first_n_out.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.first_n_out.setObjectName("first_n_out")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.first_n_out)
        
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.form_layout.setItem(1, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.last_n_label = QtWidgets.QLabel(self.centralwidget)
        self.last_n_label.setObjectName("last_n_label")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.last_n_label)
        self.last_n_out = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.last_n_out.sizePolicy().hasHeightForWidth())
        self.last_n_out.setSizePolicy(sizePolicy)
        self.last_n_out.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.last_n_out.setObjectName("last_n_out")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.last_n_out)
        
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.form_layout.setItem(3, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.special_label = QtWidgets.QLabel(self.centralwidget)
        self.special_label.setObjectName("special_label")
        self.form_layout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.special_label)
        self.special_out = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.special_out.sizePolicy().hasHeightForWidth())
        self.special_out.setSizePolicy(sizePolicy)
        self.special_out.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.special_out.setObjectName("special_out")
        self.form_layout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.special_out)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)

        self.form_layout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem2)
        self.phone_label = QtWidgets.QLabel(self.centralwidget)
        self.phone_label.setObjectName("phone_label")
        self.form_layout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.phone_label)
        self.phone_out = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phone_out.sizePolicy().hasHeightForWidth())
        self.phone_out.setSizePolicy(sizePolicy)
        self.phone_out.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.phone_out.setObjectName("phone_out")
        self.form_layout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.phone_out)

        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.form_layout.setItem(7, QtWidgets.QFormLayout.FieldRole, spacerItem3)
        self.facility_label = QtWidgets.QLabel(self.centralwidget)
        self.facility_label.setObjectName("facility_label")
        self.form_layout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.facility_label)
        self.facility_out = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.facility_out.sizePolicy().hasHeightForWidth())
        self.facility_out.setSizePolicy(sizePolicy)
        self.facility_out.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.facility_out.setObjectName("facility_out")
        self.form_layout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.facility_out)
        self.address_label = QtWidgets.QLabel(self.centralwidget)
        self.address_label.setObjectName("address_label")
        self.form_layout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.address_label)
        self.address_out = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.address_out.sizePolicy().hasHeightForWidth())
        self.address_out.setSizePolicy(sizePolicy)
        self.address_out.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.address_out.setObjectName("address_out")
        self.form_layout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.address_out)

        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.form_layout.setItem(9, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        self.gridLayout_2.addLayout(self.form_layout, 1, 2, 1, 2)
        self.prev_button = QtWidgets.QPushButton(self.centralwidget)
        self.prev_button.setObjectName("prev_button")
        self.gridLayout_2.addWidget(self.prev_button, 2, 2, 1, 1)
        self.next_button = QtWidgets.QPushButton(self.centralwidget)
        self.next_button.setObjectName("next_button")
        self.gridLayout_2.addWidget(self.next_button, 2, 3, 1, 1)
        self.index_label = QtWidgets.QLabel(self.centralwidget)
        self.index_label.setObjectName("index_label")
        self.gridLayout_2.addWidget(self.index_label, 3, 0, 1, 1)
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 18))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.first_n_out.setReadOnly(True)
        self.last_n_out.setReadOnly(True)
        self.address_out.setReadOnly(True)
        self.special_out.setReadOnly(True)
        self.phone_out.setReadOnly(True)
        self.facility_out.setReadOnly(True)

        self.load_image("cad.jpg")
        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

        self._all_docs = Doc_list(get_all_doctors())
        self.next_button.clicked.connect(self.forward)
        self.prev_button.clicked.connect(self.last)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "Alex Merino's Doctor Search"))
        self.search_button.setText(_translate("main_window", "Search"))
        self.first_n_label.setText(_translate("main_window", "First Name"))
        self.last_n_label.setText(_translate("main_window", "Last Name"))
        self.special_label.setText(_translate("main_window", "Specialty"))
        self.phone_label.setText(_translate("main_window", "Phone Number"))
        self.facility_label.setText(_translate("main_window", "Facility"))
        self.address_label.setText(_translate("main_window", "Address"))
        self.prev_button.setText(_translate("main_window", "<< Previous"))
        self.next_button.setText(_translate("main_window", "Next >>"))

    def searched(self):
        doctors = find_doctors(self.input_line.text())
        popup = Doc_pop()
        popup.setupUi(popup)
        popup.popup_label.setText( " ".join(("Search result(s) for", self.input_line.text())))
        popup.display_docs(doctors)
        popup.exec()
        self.display_doc(self._all_docs.search(popup._selected_doctor))

    def load_image(self, url):
        my_image = QtGui.QImage()
        my_image.loadFromData(self.read_image(url)) # loadFromData also accepts images as a byte-array/string of bytes
        self._pic_label = QtWidgets.QLabel(self.photo_frame) # choose a parent, such as a layout, or existing label where you want to show your image
        w = 300
        h = 300
        pixmap = QtGui.QPixmap.fromImage(my_image)
        # Scale the image to fit your label
        # It's a good idea to keep the aspect ratio so your image does not get distorted
        scaled_img = pixmap.scaled(w, h, QtCore.Qt.KeepAspectRatio) # or Qt.IgnoreAspectRatio
        self._pic_label.setPixmap(scaled_img)

    def read_image(self, img_file):
        img_bytes = open(img_file, "rb").read()
        return img_bytes

    def forward(self):
        self.display_doc(next(self._all_docs))


    def last(self):
        self.display_doc(self._all_docs.prev())

    def display_doc(self, cur_doc):
        self.first_n_out.setText(cur_doc.get_first_name())
        self.last_n_out.setText(cur_doc.get_last_name())
        self.address_out.setPlainText(cur_doc.get_address())
        self.special_out.setText(cur_doc.get_specialty())
        self.phone_out.setText(cur_doc.get_phone())
        self.facility_out.setText(cur_doc.get_facility())
        self.find_gender(cur_doc.get_gender())
        self.index_label.setText(" ".join(("Showing", str(self._all_docs._cur_val),"of", str(self._all_docs.size()), "doctor(s)")))




    def find_gender(self, gen):
        if gen.lower() == 'm':
            pic_byte = self.read_image("mrdoc.png")
        else:
            pic_byte = self.read_image("fdoc.jpg")


        new_pic = QtGui.QImage()
        new_pic.loadFromData(pic_byte) # loadFromData also accepts images as a byte-array/string of bytes
        # self._pic_label = QtWidgets.QLabel(self.photo_frame) # choose a parent, such as a layout, or existing label where you want to show your image
        w = 300
        h = 300
        pixmap = QtGui.QPixmap.fromImage(new_pic)
        # Scale the image to fit your label
        # It's a good idea to keep the aspect ratio so your image does not get distorted
        scaled_img = pixmap.scaled(w, h, QtCore.Qt.KeepAspectRatio) # or Qt.IgnoreAspectRatio
        self._pic_label.setPixmap(scaled_img)